name: "Kaggle GPU Test"
author: "namiyousef"
description: "Automatically test integration/gpu tests against Kaggle notebook with GPU runtime"
inputs:
  git_access_token:
    description: "GitHub secret token with read permissions"
    required: true
  kaggle_api_key:
    description: "Kaggle API key for pushing tests"
    required: true
  repository_name:
    description: "Repository owner and name, owner/name"
    required: true
  test_folder:
     description: "Folder to run pytest on"
     required: true
     default: "integration/"
outputs:
  automatic_releases_tag:
    description: "The release tag this action just processed"
  upload_url:
    description: "The URL for uploading additional assets to the release"
runs:
  using: "composite"
  
  steps:
  - name: authenticate-kaggle-cli
    shell: bash
    env:
      KAGGLE_API_KEY: ${{ inputs.kaggle_api_key }}
    run: |
      cd ~
      mkdir .kaggle
      python -m pip install --upgrade kaggle --user
      python -c "import json, os; kaggle_api_key = os.environ.get('KAGGLE_API_KEY'); kaggle_json = json.loads(kaggle_api_key);\
      
      with open('.kaggle/kaggle.json', 'w') as f:
        json.dump(kaggle_json, f)
      "

    # todo here needs to create the json and store it in .kaggle/
  - name: send tests
    shell: bash
    env:
      REPO_NAME: ${{ inputs.repository_name }}
      GIT_ACCESS_TOKEN: ${{ inputs.git_access_token }}
      TEST_FOLDER: ${{ inputs.test_folder }}
    run: |
      echo "hello"
      ls
      kaggle kernels init -p ${{ github.action_path }}
      cd ${{ github.action_path }}
      python utils/prepare_job.py
      kaggle kernels push
      git clone https://${GIT_ACCESS_TOKEN}@github.com/${REPO_NAME}.git
      export REPO="$(cut -d'/' -f2 <<<"$REPO_NAME")"
      cd $REPO
      ls
      python --version
      
  - name: check job status
    shell: bash
    run: |
      echo "test"
    #ls
      
    # authenticate kaggle cli
  #send-job:
    # use kaggle cli to send the tests
    # sends a job to Kaggle. I.e. this should create the files, send them
  
  #check-status:
    # needs to be a while loop, keeps checking until status is either success or error. Depending on this should output error
branding:
  icon: activity
  color: green
